### ISSUE TITLE
Expand role syntax

### ISSUE THREAD

**Issue by tomgigler** [tomgigler/GiggleMe#136]
Add the ability to expand a role, like:

`{expand:mods}`

The delivered message would replace the above with a list of users with the `mod` role

It would also be nice to exclude members of other roles roles (comma separated list)

`{expand:mods:exclude:admins}`

**Comment by tomgigler** [comment]
@justinanelson Any thoughts on syntax?  I guess it all goes to hell if someone has a role named `{expand:mods:exclude:admins}` (which is a legal role name ☹️)

**Comment by tomgigler** [comment]
Now that I look at it again, I'm not crazy about that syntax.  It's just for identifiers separated by colons

**Comment by JustinANelson** [comment]
I don't really understand the issue since I don't know javascript. Is this what would be typed into the discord client? Or the raw message that becomes a function call when the bot runs that message?

**Comment by tomgigler** [comment]
The second one: "the raw message that becomes a function call when the bot runs that message"

So it can be any syntax I want

Maybe I'm just overthinking it

**Comment by JustinANelson** [comment]
So the concern is that it runs the function using a function call as an argument? Does the bot run the function recursively? Is the argument parsed as a string ?

**Comment by tomgigler** [comment]
It's parsed

So it might see `{expand:mods}` and expand the mods role, but the user intended to ping the `expand:mods` role

Yeah, I'm overthinking it :)

**Comment by JustinANelson** [comment]
Sounds like it needs to come with a warning to not name roles the same name as function calls in the bot lol. Pull all the guild roles into an array and return the call if any of them include expand: or exclude: and send a message to stop trying to hack the bot.

**Comment by tomgigler** [comment]
Yep.  Definitely overthinking it
