### ISSUE TITLE
Pinning Messages

### ISSUE THREAD

**Issue by stitics** [tomgigler/GiggleMe#142]
Is it possible to have a toggle on the website/a variable in the command line to have the bot post it's message and immediately pin it to the channel.

Optionally(ideally) message with an @admin (or @stitics) ping in the #gigglebot channel if it received the error that the pins channel is full so that can be corrected before the next one.

**Comment by tomgigler** [comment]
Somehow I'm just seeing this now.  Must have been a busy weekend

Absolutely.  I don't know much about pinned messages but I'll look into it
