### ISSUE TITLE
Message not found?

### ISSUE THREAD

**Issue by Krazytrain** [tomgigler/GiggleMe#174]
Iv got a problem where the message is not being found. 
Iv tried the help but there is no examples to follow only commands and options.
Iv tried to find you on discord to message you but there is no user for you on github or discord server to join.

![image_2021-06-01_152714](https://user-images.githubusercontent.com/54170019/120340338-d74b3500-c2ed-11eb-934a-1edcdec64c51.png)

**Comment by tomgigler** [comment]
@Krazytrain 
You've got the `repeat` parameter specified twice.  but that should be ok.  The second one will just overwrite the first

If you give me a server invite, I can see what's going on

**Comment by tomgigler** [comment]
@Krazytrain I think I see the problem.  You probably don't have a newline (<shift><enter>) after the command and before the message

![image](https://user-images.githubusercontent.com/8260434/124314494-55863b80-db27-11eb-8911-ca6b5d8957c2.png)

![image](https://user-images.githubusercontent.com/8260434/124314519-620a9400-db27-11eb-8d3f-b850b4dca07d.png)
