### ISSUE TITLE
REQUEST: Raw post edits

### ISSUE THREAD

**Issue by stitics** [tomgigler/GiggleMe#39]
Feature where before sending a post the bot would return the "raw" post (i.e. with markdown) as opposed to the polished version (if that makes sense and/or is possible). This would enable the user to copy the result, paste into the window, edit, and submit as an edit, while maintaining the intended final formatting.

**Comment by tomgigler** [comment]
In the simple case this will be super easy.  I just need to wrap the message in back-quotes before displaying it

A couple of possible issues I see:

- if your message is 1999 characters lone, the addition of the back quotes will push it over 2000
  - it seem unlikely this would ever be an issue
-  I'm not sure what will happen with unicode emojis
   - we'll see what happens

**Comment by tomgigler** [comment]
Done
