### ISSUE TITLE
REQUEST: Make repeating messages fancier

### ISSUE THREAD

**Issue by stitics** [tomgigler/GiggleMe#41]
Either every X hours or every Y day(s) at Z time
Wishful thinking: If the bot could see if its own last iteration was the most recent post in the channel, skip the new post* or replace the old post to update the timestamp**

*preferred
**fancier

**Comment by tomgigler** [comment]
This is doable.  It might get a little weird with DST, but we'll see

fancier is doable

**Comment by tomgigler** [comment]
Repeating messages have been implemented.  The next thing to do is make them fancier as described above
