### ISSUE TITLE
For repeating messages, skip the delivery if the last delivery is in the last N messages

### ISSUE THREAD

**Issue by tomgigler** [tomgigler/GiggleMe#73]
`~g edit last repeat=hours:2 skip_if=5`

A command (something like) this would skip delivering the new message if the last delivery is in the last 5 messages in the channel

**Comment by tomgigler** [comment]
@stitics Let me know if you think this would be useful

**Comment by tomgigler** [comment]
So right now, it's working as if `skip_if=1`

This would also allow `skip_if=0` which would always deliver the new message

**Comment by stitics** [comment]
That would be amazing.

**Comment by stitics** [comment]
And now I scrolled to see that it exists already. Cool.

**Comment by stitics** [comment]
Oh, I misunderstood. Yes, that would be cool and useful. In the early part of today sometimes it's every other message.

**Comment by tomgigler** [comment]
I'm thinking that scheduling a repeating message is getting too complicated

Maybe we schedule the message as a normal message and then have a separate `~giggle repeat <msg_id> <options>` command
